group/urls.py
from django.urls import path
from . import views

app_name = 'group'

urlpatterns = [
    path('', views.ListGroup.as_view(), name = 'all'),
    path('create/', views.CreateGroup.as_view(), name = 'create'),
    path('post/in/<slug>', views.SingleGroup.as_view(), name = 'single'),
    path('join/<slug>', views.JoinGroup.as_view(), name = 'join'),
    path('leave/<slug>', views.LeaveGroup.as_view(), name = 'leave')
]

post/urls.py
from django.urls import path
from . import views

app_name = 'Post'
urlpatterns = [
    path('', views.PostList.as_view(), name = 'all'),
    path('new/', views.CreatePost.as_view(), name = 'create'),
    path('by/<username>/', views.UserPosts.as_view(), name = 'for_user'),
    path('by/<username>/<pk>', views.PostDetail.as_view(), name = 'single'),
    path('delete/<pk>/', views.DeletePost.as_view(), name = 'delete')
]

socialproject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name = 'index'),
    path('test/', views.TestPage.as_view(), name = 'test'),
    path('thanks/', views.ThankPage.as_view(), name = 'thanks'),
    path('account/', include('account.urls', namespace = 'account')),
    path('account/', include('django.contrib.auth.urls')),
    path('groups/', include('group.urls', namespace='group')),
    path('posts/', include('post.urls', namespace='post')),
]

group/models.py
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
# import misaka
from django.urls import reverse
from django import template
from django.contrib.auth import get_user_model
User = get_user_model()
# Create your models here.



register = template.Library()

class Group(models.Model):
    name = models.CharField(max_length = 100, unique = True)
    slug = models.SlugField(allow_unicode = True, unique = True)
    description = models.TextField(blank = True, default = '')
    description_html = models.TextField(editable = False, default = '', blank = True)
    group_icon = models.FileField(blank = True, null = True, upload_to = 'images')
    member = models.ManyToManyField(User, through ='GroupMember')
    create_date = models.DateTimeField(default = timezone.now)


    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = self.description#)misaka.html(
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('group:single', kwargs={'slug':self.slug})

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name = 'membership', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name = 'user_group', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('group', 'user')

group/views.py
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib import messages
from django.db import IntegrityError
from .models import Group, GroupMember
from django.urls import reverse
from django.views import generic
from django.urls import reverse

# Create your views here.
class CreateGroup(LoginRequiredMixin, generic.CreateView):
    model = Group
    fields = ('name', 'description')


class SingleGroup(generic.DetailView):
    model = Group

class ListGroup(generic.ListView):
    model = Group

class JoinGroup(LoginRequiredMixin, generic.RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return reverse('group:single', kwargs={'slug':self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group, slug=self.kwargs.get('slug'))
        user = self.request.user

        try:
            GroupMember.objects.create(user=user, group=group)
        except IntegrityError:
            messages.warning(self.request, 'Warning, already a member!')
        else:
            messages.success(self.request, 'You are now a member!')

        return super().get(request, *args, **kwargs)

class LeaveGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('group:single', kwargs={'slug':self.kwargs.get('slug')})


    def get(self, request, *args, **kwargs):
        try:
            membership = GroupMember.objects.filter(
            user=self.request.user,
            group__slug=self.kwargs.get('slug')
            ).get()

        except GroupMember.DoesNotExist:
            messages.warning(self.request, 'You are not a member of this group!')

        else:
            membership.delete()
            messages.success(self.request, 'You have left the group!')
        return super().get(request, *args, **kwargs)

group/templates/group/group_base.html
{% extends 'base.html' %}


{% block content %}

  <div class="container">
    <div class="row">
      {% block pregroup %}

      {% endblock %}
      {% block group_content %}

      {% endblock %}
      {% block postgroup %}

      {% endblock %}
    </div>
  </div>

{% endblock %}

group/templates/group/group_detail.html
{% extends 'group/group_base.html' %}

{% block pregroup %}
  <h1> {{ group.name }} </h1>
  <h5> Member count: {{ group.member.count }} </h5>
  <div class="content">
    {% if user in group.member.all %}
      <a class="btn btn-lg btn-fill btn-warning" href="{% url 'group:leave' slug=group.slug %}">Leave group</a>
    {% else %}
      <a class="btn btn-lg btn-fill btn-primary" href="{% url 'group:join' slug=group.slug %}">Join group</a>
    {% endif %}
  </div>
{% endblock %}
<!-- main -->
{% block group_content %}
  <div class="col-md-8">
    {% if group.post.count == 0 %}
      <p>No post in this group yet!</p>
    {% else %}
      {% for post in group.post.all %}
        {% include 'post/_post.html' %}
      {% endfor %}
    {% endif %}
  </div>
{% endblock %}

group/templates/group/group_form.html
{% extends 'group/group_base.html' %}
{% load bootstrap4 %}

{% block group_content %}
  <h4>Create group below</h4>
  <form id="groupForm" action="{% url 'group:create' %}" method="post">
    {% bootstrap_form form %}
    {% csrf_token %}
    <input type="submit" class="btn btn-lg btn-primary" value="Create">
  </form>
{% endblock %}

group/templates/group/group_list.html
{% extends "group/group_base.html" %}

{% block pregroup %}
<div class="col-md-4">
	<div class="content">
		{% if user.is_authenticated %}
		<h2>
			Welcome back
			<a href="{% url 'post:for_user' username=user.username %}">@{{user.username }}</a>
		</h2>

    {% endif %}
			<h2>Groups</h2>

			<p>Welcome to the Groups Page! Select a Group with a shared interest!</p>
	</div>
	<a href="{% url 'group:create' %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-plus-sign"></span> Create New Group!</a>
</div>
{% endblock %}

{% block group_content %}
<div class="col-md-8">
	<div class="list-group">
		{% for group in object_list %}
		  <a class="list-group-item" href="{% url 'group:single' slug=group.slug %}">
			     <h3 class="title list-group-item-heading">{{ group.name }}</h3>
			<div class="list-group-item-text container-fluid">
				{{ group.description_html|safe }}
				<div class="row">
					<div class="col-md-4">
						<span class="badge">{{ group.member.count }}</span> member{{ group.member.count|pluralize }}
					</div>
					<div class="col-md-4">
						<span class="badge">{{ group.post.count }}</span> post{{ group.post.count|pluralize }}
					</div>
				</div>
			</div>
		</a>
		{% endfor %}
	</div>
</div>
{% endblock %}