post/urls.py
from django.urls import path
from . import views

app_name = 'Post'
urlpatterns = [
    path('', views.PostList.as_view(), name = 'all'),
    path('new/', views.CreatePost.as_view(), name = 'create'),
    path('by/<username>/', views.UserPosts.as_view(), name = 'for_user'),
    path('by/<username>/<pk>', views.PostDetail.as_view(), name = 'single'),
    path('delete/<pk>/', views.DeletePost.as_view(), name = 'delete')
]

socialproject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name = 'index'),
    path('test/', views.TestPage.as_view(), name = 'test'),
    path('thanks/', views.ThankPage.as_view(), name = 'thanks'),
    path('account/', include('account.urls', namespace = 'account')),
    path('account/', include('django.contrib.auth.urls')),
    path('groups/', include('group.urls', namespace='group')),
    path('posts/', include('post.urls', namespace='post')),
]

post/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.conf import settings
# import misaka
from group.models import Group
from django.contrib.auth import get_user_model
# Create your models here.
User = get_user_model()

class Post(models.Model):
    user = models.ForeignKey(User, related_name = 'post', on_delete = models.CASCADE)
    title = models.CharField(max_length = 200)
    text = models.TextField()
    text_html = models.TextField(editable = False)
    create_date = models.DateTimeField(auto_now = True)
    group = models.ForeignKey(Group, related_name = 'post', null = True, blank = 'True', on_delete=models.CASCADE)


    def save(self, *args, **kwargs):
        # self.text_html = self.text #)misaka.html(
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('post:single', kwargs={'username':self.user.username,'pk':self.pk})

    def __str__(self):
        return self.text

    class Meta:
        ordering = ['-create_date']
        unique_together = ['user', 'text']

post/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.urls import reverse_lazy
from .models import User, Post
from . import forms
from django.http import Http404
from django.contrib import messages
from braces.views import SelectRelatedMixin
# Create your views here.
User = User
class PostList(SelectRelatedMixin, generic.ListView):
    model = Post
    select_related = ['user', 'group']

class UserPosts(generic.ListView):
    model = Post
    template_name = 'post/user_post_list.html'

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related('post').get(username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.post.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post_user
        return context

class PostDetail(SelectRelatedMixin, generic.DetailView):
    model = Post
    select_related = ['user', 'group']

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact=self.kwargs.get('username'))

class CreatePost(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    fields = ('title', 'text', 'group')
    model = Post

    def form_valid(self, form):
        self.object = form.save(commit = False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

class DeletePost(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):

    model = Post
    select_related = ['user', 'group']
    success_url = reverse_lazy('post:all')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id = self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, 'Post Deleted')
        return super().delete(*args, **kwargs)

post/templates/post/_post.html
<div class="post_media">
  <h3>{{post.text|safe}}</h3>
  <div class="media-body">
    <strong>{{post.user.username}}</strong>
    <h5 class="media-heading">
      <span class="username">
        <a href="{% url 'post:for_user' username=post.user.username %}">@{{post.user.username}}</a>
      </span>
      <time class="time"><a href="{% url 'post:single' username=post.user.username pk=post.pk %}">
        {{ post.create_date }}
      </a></time>
    </h5>
    <div class="media-footer">
      {% if user.is_authenticated and post.user == user %}
        <a href="{% url 'post:delete' pk=post.pk %}" title='delete' class="btn btn-warning">
          Delete Post
        </a>
      {% endif %}
    </div>
  </div>
</div>

post/templates/post/post_base.html
{% extends 'base.html' %}

{% block content %}
  <div class="post_page">
    <div class="container">
      <div class="row">
        {% block pre_post %}
        {% endblock %}
        {% block post_content %}
        {% endblock %}
        {% block post_post %}
        {% endblock %}

      </div>
    </div>
  </div>
{% endblock %}

post/templates/post/post_confirm_delete.html
{% extends 'post/post_base.html' %}

{% block post_content %}
  <h3>Are you sure you want to delete this post? </h3>
  <div class="posts">
    {% include 'post/_post.html' with post=object hide_delete=True %}
  </div>
  <form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete">
    <a href="{% url 'post:single' username=user.username pk=object.pk %}"
    class="btn btn-simple btn-secondary">Cancel</a>
  </form>
{% endblock %}

post/templates/post/post_detail.html
{% extends 'post/post_base.html' %}

{% block post_content %}
  <div class="col-md-8">
    {% include 'post/_post.html' %}
  </div>
{% endblock %}

post/templates/post/post_form.html
{% extends 'post/post_base.html' %}
{% load bootstrap4 %}

{% block post_content %}
  <h4>Create new Post</h4>
  <form id="postForm" action="{% url 'post:create' %}" method="post">
    {% bootstrap_form form %}
    {% csrf_token %}
    <input type="submit" class="btn btn-primary" value="Publish" />
  </form>
{% endblock %}

post/templates/post/post_list.html
{% extends 'post/post_base.html' %}

{% block pre_content %}
<div class="col-md-4">
  {% if user.is_authenticated %}
    <div class="card">
      <div class="content">
        <h5 class="title">Your Groups</h5>
        <ul class="">
          {% for group_member in get_user_groups %}
            <li class="group li-with-bullet">
              <a href="{% url 'group:single' slug=group_member.group.slug %}"></a>
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  {% endif %}
  <div class="card">
    <div class="content">
      <h5 class="title">All Groups</h5>
      <ul class="">
        {%  for other_group in get_other_groups %}
        <li class="group li-with-bullet">
          <a href="{% url 'group:single' slug=other_group.slug %}"></a>
        </li>
        {% endfor %}
      </ul>
    </div>
  </div>
</div>

{% endblock %}
{% block post_content %}
<div class="col-md-8">
  {% for post in post_list %}
    {% include 'post/_post.html' %}
  {% endfor %}
</div>
{% endblock %}

post/templates/post/user_post_list.html
{% extends 'post/post_base.html' %}

{% block pre_post %}
  <div class="col-md-4">
    <h1>@{{ post_user.username }}</h1>
  </div>
{% endblock %}

{% block post_content %}
  <div class="col-md-8">
    {% for post in post_list %}
      {% include 'post/_post.html' %}
    {% endfor %}
  </div>
{% endblock %}