account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', auth_view.LoginView.as_view(template_name = 'account/login.html'), name = 'login'),
    path('logout/', auth_view.LogoutView.as_view(), name = 'logout'),
    path('signup/', views.SignUp.as_view(), name = 'signup'),
]

post/urls.py
from django.urls import path
from . import views

app_name = 'Post'
urlpatterns = [
    path('', views.PostList.as_view(), name = 'all'),
    path('new/', views.CreatePost.as_view(), name = 'create'),
    path('by/<username>/', views.UserPosts.as_view(), name = 'for_user'),
    path('by/<username>/<pk>', views.PostDetail.as_view(), name = 'single'),
    path('delete/<pk>/', views.DeletePost.as_view(), name = 'delete')
]

socialproject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name = 'index'),
    path('test/', views.TestPage.as_view(), name = 'test'),
    path('thanks/', views.ThankPage.as_view(), name = 'thanks'),
    path('account/', include('account.urls', namespace = 'account')),
    path('account/', include('django.contrib.auth.urls')),
    path('groups/', include('group.urls', namespace='group')),
    path('posts/', include('post.urls', namespace='post')),
]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Star Social</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


    {# CSS #}
    {% comment %} <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> {% endcomment %}
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    {# JS #}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    {# Fonts #}
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    {% comment %} Font Awesome {% endcomment %}
    <script src="https://kit.fontawesome.com/02075671c0.js"></script>
    {# Css File #}
    <link rel="stylesheet" href="{% static 'socialproject/css/master.css' %}" >

  </head>
  <body>
      <nav class="navbar  mynav" role="navigation" id="navbar">
          <div class="container">
              <a class="navbar-brand mynav" href="{% url 'index' %}">Star Social</a>
              <ul class="nav navbar-nav navbar-right">
                  {% if user.is_authenticated %}
                  <li><a href="{% url 'post:create' %}" class="btn btn-simple">Add Post</a></li>
                  <li><a href="{% url 'group:all' %}" class="btn btn-simple">Groups</a></li>
                  <li><a href="{% url 'group:create' %}" class="btn btn-simple">Create Group</a></li>
                  <li><a href="{% url 'account:logout' %}" class="btn btn-simple">Log out</a></li>
                  {% else %}
                  <li><a href="{% url 'group:all' %}"class="btn btn-simple">Groups</a></li>
                  <li><a href="{% url 'account:login' %}" class="btn btn-simple">Log in</a></li>
                  <li><a href="{% url 'account:signup' %}" class="btn btn-simple">Sign up</a></li>
                  {% endif %}
              </ul>
          </div>
      </nav>
      <div class="container mycontent">
          {% block content %}
          {% endblock %}
      </div>

<canvas id="canvas"></canvas>

  </body>
  <script src="{% static "socialproject/js/master.js" %}" type="text/javascript" ></script>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
  <h1> Welcome to Star Social! </h1>
{% endblock %}

templates/test.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <h1>You're now logged in!</h1>
</div>
  
{% endblock %}

templates/thanks.html
{% extends 'base.html' %}

{% block content %}
  <h1>Thanks for visiting, come back soon! </h1>
{% endblock %}